import vscode from 'vscode';
import { t } from '../i18n';
import { logger } from '../logger';

/**
 * ABAP Agent Guide
 *
 * Copilot agents read a workspace instruction file (AGENTS.md / .github/
 * copilot-instructions.md) as persistent system context. This module keeps a
 * small, auto-generated guide in that file that tells the agent to PREFER the
 * bundled `dnova-abap-mcp` MCP server for any SAP ABAP task — so the agent
 * reaches for our ABAP tools instead of guessing or doing nothing.
 *
 * The guide is wrapped in HTML-comment markers so it can be updated/removed
 * without touching anything else the user wrote in the file.
 */

const GUIDE_START = '<!-- DNOVA ABAP AGENT GUIDE:START -->';
const GUIDE_END = '<!-- DNOVA ABAP AGENT GUIDE:END -->';

// ABAP source file extensions used to detect an ABAP workspace.
const ABAP_FILE_GLOB =
	'**/*.{abap,abapsource,cds,ddls,ddlx,clas,intf,prog,fugr,include}';

const GUIDE_BLOCK = `${GUIDE_START}
<!-- Auto-generated by "DNova for Copilot Chat". Manage with
     "DNova: Update ABAP Agent Guide" / "DNova: Remove ABAP Agent Guide". -->

## ABAP Development Guide (DNova)

This workspace contains SAP ABAP development source code.

### Prefer the built-in ABAP MCP

The "DNova for Copilot Chat" extension bundles a complete SAP ABAP MCP server
named **\`dnova-abap-mcp\`**. Its tools appear under the \`mcp__dnova-abap-mcp__\`
prefix. For any task that touches **SAP ABAP repository objects** — reading or
editing classes, function modules, programs, tables, CDS views, data elements,
domains; activating or syntax-checking objects; running runtime queries;
searching the ABAP repository — **prefer the \`mcp__dnova-abap-mcp__*\` tools
first** before falling back to local file inspection.

Common mappings:
- Read object source / metadata → \`mcp__dnova-abap-mcp__Get*\` tools
- Create an object → \`mcp__dnova-abap-mcp__Create*\` tools
- Update / edit an object → \`mcp__dnova-abap-mcp__Update*\` tools
- Activate / check an object → \`mcp__dnova-abap-mcp__Activate*\` / \`Check*\` tools
- Search the ABAP repository → \`mcp__dnova-abap-mcp__Search*\` tools

If the \`mcp__dnova-abap-mcp__*\` tools are unavailable (MCP disabled or not
connected), tell the user and inspect the local files as a fallback.

${GUIDE_END}`;

/** The guide file name, relative to the workspace root. */
function getGuideFile(): string {
	const file = vscode.workspace
		.getConfiguration('dnova-copilot.abap.agentGuide')
		.get<string>('file', 'AGENTS.md');
	return file || 'AGENTS.md';
}

/** Whether the guide should be auto-created on activation for ABAP workspaces. */
function isAutoCreateEnabled(): boolean {
	return vscode.workspace
		.getConfiguration('dnova-copilot.abap.agentGuide')
		.get<boolean>('autoCreate', true);
}

/** Target URI of the guide file in the first workspace folder. */
function getTargetUri(): vscode.Uri | undefined {
	const folder = vscode.workspace.workspaceFolders?.[0];
	if (!folder) {
		return undefined;
	}
	return vscode.Uri.joinPath(folder.uri, getGuideFile());
}

/** Detect an ABAP workspace by looking for ABAP source files (anywhere). */
async function isAbapWorkspace(): Promise<boolean> {
	const folder = vscode.workspace.workspaceFolders?.[0];
	if (!folder) {
		return false;
	}
	const matches = await vscode.workspace.findFiles(
		new vscode.RelativePattern(folder, ABAP_FILE_GLOB),
		'**/node_modules/**',
		1,
	);
	return matches.length > 0;
}

async function readFile(uri: vscode.Uri): Promise<string | undefined> {
	try {
		const bytes = await vscode.workspace.fs.readFile(uri);
		return Buffer.from(bytes).toString('utf8');
	} catch {
		return undefined;
	}
}

async function writeFile(uri: vscode.Uri, content: string): Promise<void> {
	await vscode.workspace.fs.writeFile(uri, Buffer.from(content, 'utf8'));
}

function escapeRegExp(value: string): string {
	return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Insert or replace the guide block inside an existing file. Anything outside
 * the markers is left untouched. If no block exists yet, it is appended.
 */
function upsertGuideBlock(existing: string | undefined): string {
	if (!existing) {
		return GUIDE_BLOCK;
	}
	const pattern = new RegExp(
		`${escapeRegExp(GUIDE_START)}[\\s\\S]*?${escapeRegExp(GUIDE_END)}`,
	);
	if (pattern.test(existing)) {
		return existing.replace(pattern, GUIDE_BLOCK);
	}
	return existing.replace(/\s*$/, '\n') + '\n' + GUIDE_BLOCK + '\n';
}

/** Remove the guide block from an existing file, leaving the rest intact. */
function removeGuideBlock(existing: string): string {
	const pattern = new RegExp(
		`${escapeRegExp(GUIDE_START)}[\\s\\S]*?${escapeRegExp(GUIDE_END)}\\s*`,
	);
	return existing.replace(pattern, '').replace(/\n{3,}/g, '\n\n').trimEnd();
}

async function writeGuide(uri: vscode.Uri): Promise<'created' | 'updated'> {
	const existing = await readFile(uri);
	const created = existing === undefined;
	await writeFile(uri, upsertGuideBlock(existing) + '\n');
	return created ? 'created' : 'updated';
}

/**
 * Activation hook — silently creates/refreshes the guide when the current
 * workspace looks like an ABAP project and `autoCreate` is enabled.
 */
export async function ensureAbapAgentGuide(): Promise<void> {
	if (!isAutoCreateEnabled()) {
		return;
	}
	const uri = getTargetUri();
	if (!uri) {
		return;
	}
	try {
		if (!(await isAbapWorkspace())) {
			return;
		}
		const result = await writeGuide(uri);
		logger.info(`ABAP agent guide ${result}: ${uri.toString(true)}`);
	} catch (error) {
		logger.warn('Failed to write ABAP agent guide', error);
	}
}

/** Command handler — create or refresh the ABAP agent guide on demand. */
export async function createAbapAgentGuide(): Promise<void> {
	const uri = getTargetUri();
	if (!uri) {
		void vscode.window.showInformationMessage(t('agentGuide.noWorkspace'));
		return;
	}
	const existing = await readFile(uri);
	if (existing === undefined && !(await isAbapWorkspace())) {
		// Don't pollute a non-ABAP workspace unless the file already exists
		// (meaning the user asked for it before).
		void vscode.window.showInformationMessage(t('agentGuide.notAbap'));
		return;
	}
	try {
		const result = await writeGuide(uri);
		const file = getGuideFile();
		void vscode.window.showInformationMessage(
			result === 'created' ? t('agentGuide.created', file) : t('agentGuide.updated', file),
		);
	} catch (error) {
		void vscode.window.showErrorMessage(
			t(
				'agentGuide.writeFailed',
				getGuideFile(),
				error instanceof Error ? error.message : String(error),
			),
		);
	}
}

/** Command handler — remove the guide block, keeping the rest of the file. */
export async function removeAbapAgentGuide(): Promise<void> {
	const uri = getTargetUri();
	if (!uri) {
		return;
	}
	const existing = await readFile(uri);
	if (existing === undefined || !existing.includes(GUIDE_START)) {
		void vscode.window.showInformationMessage(t('agentGuide.notFound'));
		return;
	}
	try {
		const cleaned = removeGuideBlock(existing);
		if (cleaned.trim()) {
			await writeFile(uri, cleaned + '\n');
		} else {
			await vscode.workspace.fs.delete(uri);
		}
		void vscode.window.showInformationMessage(t('agentGuide.removed'));
	} catch (error) {
		void vscode.window.showErrorMessage(
			t(
				'agentGuide.writeFailed',
				getGuideFile(),
				error instanceof Error ? error.message : String(error),
			),
		);
	}
}
